<?php if ($block->isAllowed()) : ?>
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="">
            <div class="page-actions-buttons">                
                <button id="schedule" title="<?php echo __("Generate Feed"); ?>" type="button" class="action- scalable primary" onclick="location.href = '<?php echo $block->getGenerateFeedUrl(); ?>';" data-ui-id="schedule-button">
                    <span><?php echo __("Generate Feed"); ?></span>
                </button>
            </div>
        </div>
    </div>
<?php endif;
